Update roothide.yml

diff --git a/.github/workflows/roothide.yml b/.github/workflows/roothide.yml
--- a/.github/workflows/roothide.yml
+++ b/.github/workflows/roothide.yml
@@ -66,8 +66,18 @@ jobs:
           export BASEDIR="$(pwd)"
           export THEOS="${BASEDIR}/theos"
           typeset itemcount=$(plutil -extract items raw -expect array ./Application/Dopamine/UI/Settings/Credits.plist)
-          for ((i=0; i<$itemcount; i++)); do headerCellClass=$(plutil -extract items.$i.headerCellClass raw ./Application/Dopamine/UI/Settings/Credits.plist 2>/dev/null || echo "") if [ "$headerCellClass" = "DOCreditsCell" ]; then DOCreditsCellIndex=$i fi done;
-          plutil -insert items.$DOCreditsCellIndex.names -xml "<dict><key>name</key><string>${{ github.actor }}</string><key>link</key><string>https://github.com/${{ github.repository }}</string></dict>" -append ./Application/Dopamine/UI/Settings/Credits.plist
+          for ((i=0; i<$itemcount; i++)); do 
+              headerCellClass=$(plutil -extract items.$i.headerCellClass raw ./Application/Dopamine/UI/Settings/Credits.plist 2>/dev/null || echo "")
+              if [ "$headerCellClass" = "DOCreditsCell" ]; then 
+                  DOCreditsCellIndex=$i
+              fi 
+          done
+          if [ -n "$DOCreditsCellIndex" ]; then
+              plutil -insert items.$DOCreditsCellIndex.names -xml "<dict><key>name</key><string>${{ github.actor }}</string><key>link</key><string>https://github.com/${{ github.repository }}</string></dict>" -append ./Application/Dopamine/UI/Settings/Credits.plist
+          else
+              echo "Error: DOCreditsCell not found"
+              exit 1
+          fi
           gmake -j$(sysctl -n hw.physicalcpu)
           TAG=$(git describe --tags --abbrev=0)
           mv ./Application/Dopamine.tipa  "./Application/roothide-Dopamine2-v${TAG}.tipa"
